# Hand-written for the seed USB stick — not generated by nixos-generate-config.
# The stick roams between machines, so: broad initrd storage/USB drivers,
# redistributable firmware (Wi-Fi), both CPU microcodes, and filesystems by
# LABEL rather than by-uuid.
#
# Labels stay jump / JUMP-ESP (the host's old name, before the rename to seed).
# The stick is already formatted with those names.
#   ESP  (FAT32, ~1G, type EF00)  mkfs.fat -F 32 -n JUMP-ESP /dev/sdX1
#   root (ext4, rest)             mkfs.ext4 -L jump /dev/sdX2
# Or replace both devices with /dev/disk/by-uuid/... from `blkid` once the
# stick is formatted. No UUIDs are guessed here.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ehci_pci" "ohci_pci" "uhci_hcd"
    "usb_storage" "uas" "usbhid" "hid_generic"
    "ahci" "nvme" "sd_mod" "sr_mod"
    "sdhci_pci" "rtsx_pci_sdmmc" "mmc_block"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/jump";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/JUMP-ESP";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  hardware.enableRedistributableFirmware = true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
