# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/b3821fe9-ed59-4d17-994c-faadecc16a60";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/b3821fe9-ed59-4d17-994c-faadecc16a60";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/90B6-5EC8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

    "/swap" = {
      device = "/dev/disk/by-uuid/b3821fe9-ed59-4d17-994c-faadecc16a60";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime" ];
    };
  };

  swapDevices = [
    { device = "/swap/swapfile"; size = 8192; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
